# Generated by Django 3.0.8 on 2021-04-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210322_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes', verbose_name='Изображение'),
        ),
    ]
