# Generated by Django 3.0.8 on 2021-04-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210408_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingradient',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingradients',
            new_name='ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение'),
        ),
    ]
