# Generated by Django 3.0.8 on 2021-06-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20210609_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='colour',
            field=models.CharField(choices=[('orange', 'Breakfast'), ('green', 'Lunch'), ('purple', 'Dinner')], default='purple', max_length=6),
        ),
    ]
