# Generated by Django 3.0.8 on 2021-06-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_tag_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purchases', to='recipes.Recipe'),
        ),
    ]
